# Generated by Django 5.1.3 on 2024-11-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=5)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary', models.FloatField(max_length=10)),
                ('manager_id', models.IntegerField(max_length=5)),
                ('department_id', models.IntegerField(max_length=5)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company_details.company')),
            ],
        ),
    ]
