# Generated by Django 5.1.3 on 2024-11-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_name',
            new_name='company',
        ),
    ]
